[project]
name = "autoe2e"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "abstract-singleton==1.0.1",
    "beautifulsoup4==4.12.2",
    "blinker==1.9.0",
    "cachelib==0.13.0",
    "click==8.3.0",
    "colorama==0.4.6",
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "deepdiff==6.3.0",
    "flask==3.0.3",
    "flask-cors==4.0.1",
    "flask-session==0.8.0",
    "huggingface-hub>=0.34,<1.0",
    "itsdangerous==2.2.0",
    "jinja2==3.1.6",
    "langchain>=0.3.27",
    "langchain-anthropic>=0.3.22",
    "langchain-aws>=0.2.35",
    "langchain-community>=0.3.21",
    "langchain-core>=0.3.79",
    "langchain-experimental>=0.3.4",
    "langchain-openai>=0.3.35",
    "langchain-text-splitters>=0.3.11",
    "markupsafe==3.0.3",
    "msgspec==0.19.0",
    "networkx==2.8.8",
    "node2vec==0.4.6",
    "notebook==7.2.0",
    "numpy>=1.26.4",
    "openai>=2.7.2",
    "pandas>=2.3.3",
    "pinecone-client==4.0.0",
    "pymongo>=4.15.4",
    "pytesseract==0.3.10",
    "pytest==7.3.1",
    "python-dotenv==1.0.0",
    "pyyaml==6.0.1",
    "redis==5.0.6",
    "regex==2022.10.31",
    "rstr==3.2.2",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "selenium==4.9.0",
    "selenium-wire==5.1.0",
    "socksio>=1.0.0",
    "tiktoken>=0.12.0",
    "tokenizers>=0.22.1",
    "tqdm==4.65.0",
    "webdriver-manager==4.0.1",
    "werkzeug==3.1.3",
]
